
remote_theme: pmarsceill/just-the-docs
title: Моя Документация
nav_order: 1

# Configuration for the Just the Docs theme
just_the_docs:
  aux_links: {
    "GitHub Repository": "https://github.com/username/documentation-site"
  }
  nav_order: true
  search_enabled: true
  show_last_updated_time: true
  show_sidebar_nav: true
