remote_theme: pmarsceill/just-the-docs
title: Tele2 Дома
nav_order: 1

# Configuration for the Just the Docs theme
just_the_docs:
  aux_links: {
    "GitHub Repository": "https://github.com/kushnro/t2d-user-manual"
  }
  nav_order: true
  search_enabled: true
  show_last_updated_time: true
  show_sidebar_nav: true
